[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Vestuario/Maps/L_Vestuario.L_Vestuario
EditorStartupMap=/Game/Vestuario/Maps/L_Vestuario.L_Vestuario
GlobalDefaultGameMode=/Script/ElVestuario.VestuarioGameMode

[/Script/Engine.RendererSettings]
; Lumen (iluminacion global y reflejos en tiempo real) + sombras virtuales
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Shadow.Virtual.Enable=1
r.GenerateMeshDistanceFields=True
r.AllowStaticLighting=False
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.DefaultFeature.MotionBlur=False
r.AntiAliasingMethod=4
r.VolumetricFog=True

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12

[/Script/NavigationSystem.RecastNavMesh]
; El navmesh se genera al empezar la partida (asi no hay que "construirlo" a mano)
RuntimeGeneration=Dynamic

[/Script/NavigationSystem.NavigationSystemV1]
bAutoCreateNavigationData=True
